repos:
-   repo: local
    hooks:
    -   id: run-notebooks
        name: Run Notebooks
        entry: python run_notebooks.py
        language: system
        files: 'notebooks/.*\.ipynb$'
        always_run: true
